function make_getgpuinfo
%MAKE_GETGPUINFO Makefile for GETGPUINFO.

% S. Engblom 2011-04-04

s = pwd;
mx = mexext;
ver = version;

if strcmp(mx,'mexa64')
  if ~strncmp(version,'7.11',4) && ~strncmp(version,'7.13',4)
    warning(['Extension .' mexext ...
             ' tested with Matlab version(s) 7.11 and 7.13 only.']);
  end
  cudaroot = '/usr/local/cuda';
  mex('CXX=nvcc', ...
      ['CXXFLAGS=-arch=sm_20 -Xcompiler=''-fPIC -fno-omit-frame-pointer ' ...
       '-pthread'''], ...
      ['CXXLIBS=-Wl,-rpath-link,' matlabroot '/bin/glnxa64 ' ...
       '-L' matlabroot '/bin/glnxa64 -L' cudaroot '/lib64 ' ...
       '-lmx -lmex -lmat -lm -lstdc++ -lmwblas -lcudart'], ...
      'LD=gcc', ...
      ['LDFLAGS=-pthread -shared -m64 -Wl,--version-script,' ...
       matlabroot '/extern/lib/glnxa64/mexFunction.map -Wl,--no-undefined'], ...
      ['-I' cudaroot '/include'], ...
      ['-L' matlabroot '/sys/os/glnxa64 -L' cudaroot '/lib64'], ...
      '-outdir',s, ...
      'source/getgpuinfo.cu');
else
  error('No make currently available for this platform.');
end
